---
name: test-cf-rabbitmq-smoke-tests-release-ci

instance_groups:
- azs:
  - z1
  instances: 1
  name: smoke-tests
  networks:
  - name: ((network))
  stemcell: trusty
  vm_type: ((vm_type))
  jobs: []

releases:
- name: test-cf-rabbitmq-smoke-tests	
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 4
  serial: false
  update_watch_time: 30000-180000
